import {NextResponse} from "next/server";
import {getAdminSession} from "@/lib/admin-auth";
import {createAppointment,listAppointments} from "@/lib/appointments";
import {isValidEmail,requiredText,zurichDateTimeToIso} from "@/lib/validation";
import {syncGoogleCalendar} from "@/lib/google-calendar";
import {sendManualAppointmentConfirmationEmail} from "@/lib/appointment-email";
export const dynamic="force-dynamic";
async function authorized(){return Boolean(await getAdminSession())}
export async function GET(){if(!await authorized())return NextResponse.json({error:"Non autorisé"},{status:401});return NextResponse.json({appointments:await listAppointments()})}
export async function POST(request:Request){if(!await authorized())return NextResponse.json({error:"Non autorisé"},{status:401});try{const body=await request.json() as Record<string,unknown>;const startsLocal=requiredText(body.startsAt,64);const input={name:requiredText(body.name,120),email:requiredText(body.email,180),phone:requiredText(body.phone,50),address:requiredText(body.address,300),requestType:requiredText(body.requestType,40),reason:requiredText(body.reason,2000),preferredDate:startsLocal.slice(0,10),preferredTimeStart:startsLocal.slice(11,16),preferredTimeEnd:"",alternateDate:"",alternateTimeStart:"",alternateTimeEnd:"",notes:""};if(!input.name||!isValidEmail(input.email)||!input.phone||!input.address||!input.requestType||!input.reason||!startsLocal)return NextResponse.json({error:"Champs obligatoires manquants"},{status:400});const startsAt=zurichDateTimeToIso(startsLocal);const appointment=await createAppointment(input,"manual");const {updateAppointment}=await import("@/lib/appointments");const updated=await updateAppointment(appointment.id,{action:"accept",startsAt,adminNotes:requiredText(body.adminNotes,2000)});try{await syncGoogleCalendar(updated)}catch(error){console.error("Google Calendar sync failed",error)}try{await sendManualAppointmentConfirmationEmail(updated)}catch(error){console.error("Manual appointment confirmation email failed",error)}return NextResponse.json({appointment:updated},{status:201})}catch(error){console.error(error);return NextResponse.json({error:"Création impossible"},{status:400})}}
