import {NextResponse} from "next/server";
import {getAdminSession} from "@/lib/admin-auth";
import {sendAppointmentStatusEmail} from "@/lib/appointment-email";
import {deleteAppointment,getAppointment,updateAppointment} from "@/lib/appointments";
import {isValidEmail,requiredText,zurichDateTimeToIso} from "@/lib/validation";
import {removeGoogleCalendarEvent,syncGoogleCalendar} from "@/lib/google-calendar";
export const dynamic="force-dynamic";
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!await getAdminSession())return NextResponse.json({error:"Non autorisé"},{status:401});try{const{id}=await params;const body=await request.json() as Record<string,unknown>;const action=requiredText(body.action,20);const startsLocal=requiredText(body.startsAt,64);const endsLocal=requiredText(body.endsAt,64);const customerEmail=requiredText(body.customerEmail,180);if(customerEmail&&!isValidEmail(customerEmail))return NextResponse.json({error:"L’adresse e-mail du client n’est pas valide."},{status:400});const appointment=await updateAppointment(id,{action,startsAt:startsLocal?zurichDateTimeToIso(startsLocal):undefined,endsAt:endsLocal?zurichDateTimeToIso(endsLocal):undefined,adminNotes:requiredText(body.adminNotes,2000),customerName:requiredText(body.customerName,120),customerEmail,customerPhone:requiredText(body.customerPhone,50),customerAddress:requiredText(body.customerAddress,300),requestType:requiredText(body.requestType,40),reason:requiredText(body.reason,2000)});const kind={accept:"confirmed",propose:"modified",cancel:"cancelled",reject:"rejected"}[action] as "confirmed"|"modified"|"cancelled"|"rejected"|undefined;let emailSent=true;if(kind){try{await sendAppointmentStatusEmail(appointment,kind)}catch(error){emailSent=false;console.error("Customer email failed",error)}}let calendarSynced=false;try{calendarSynced=(await syncGoogleCalendar(appointment)).synced}catch(error){console.error("Google Calendar sync failed",error)}return NextResponse.json({appointment,emailSent,calendarSynced})}catch(error){console.error(error);const message=error instanceof Error&&["Date invalide","Date required"].includes(error.message)?"Veuillez choisir une date et une heure valides.":"Modification impossible";return NextResponse.json({error:message},{status:400})}}

export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){if(!await getAdminSession())return NextResponse.json({error:"Non autorisé"},{status:401});try{const{id}=await params;const appointment=await getAppointment(id);if(!appointment)return NextResponse.json({error:"Rendez-vous introuvable"},{status:404});try{await removeGoogleCalendarEvent(appointment)}catch(error){console.error("Google Calendar deletion failed",error)}await deleteAppointment(id);return NextResponse.json({ok:true})}catch(error){console.error("Appointment deletion failed",error);return NextResponse.json({error:"Suppression impossible"},{status:400})}}
