"use client";
import {useState} from "react";
import {Header} from "../ui/header";
import {MobileActions} from "../ui/mobile-actions";

export default function DevisPage(){
  const[status,setStatus]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Envoi en cours…");const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/devis",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});setStatus(r.ok?"Merci ! Votre demande est bien enregistrée. Nous vous répondons sous 24 h.":"Une erreur est survenue. Appelez-nous au +41 78 322 33 68.");if(r.ok)e.currentTarget.reset()}
  return <main><Header/><section className="quote-layout"><div className="quote-intro"><p className="eyebrow light">Devis gratuit sous 24 h</p><h1>Parlez-nous de votre besoin</h1><p>Déménagement, nettoyage, location de camion, transport, débarras ou petits travaux : quelques informations suffisent pour préparer une première réponse.</p><div className="quote-contact"><a href="tel:+41783223368"><strong>Appelez-nous</strong><span>+41 78 322 33 68</span></a><a href="https://wa.me/41783223368"><strong>Écrivez sur WhatsApp</strong><span>Réponse rapide</span></a></div></div><form className="quote-form" onSubmit={submit}><div className="two-fields"><label>Nom complet<input required name="name" autoComplete="name"/></label><label>Téléphone<input required name="phone" autoComplete="tel"/></label></div><label>Adresse e-mail<input required type="email" name="email" autoComplete="email"/></label><label>Service demandé<select required name="service" defaultValue=""><option value="" disabled>Choisir un service</option><option>Déménagement</option><option>Nettoyage de fin de bail</option><option>Nettoyage de bureaux</option><option>Nettoyage de fin de chantier</option><option>Location Iveco Daily 17 m³</option><option>Location Citroën Jumper 20 m³ avec hayon</option><option>Transport ou livraison</option><option>Montage de meubles</option><option>Débarras</option><option>Petits travaux ou jardinage</option></select></label><div className="two-fields"><label>Commune<input required name="city" placeholder="Lausanne"/></label><label>Date souhaitée<input type="date" name="date"/></label></div><label>Décrivez votre demande<textarea required minLength={15} name="message" rows={6} placeholder="Demi-journée ou journée complète, date souhaitée et autre information utile…"/></label><label className="consent"><input required type="checkbox" name="consent" value="yes"/> J’accepte d’être contacté au sujet de cette demande.</label><input className="honeypot" name="website" tabIndex={-1}/><button className="button button-primary" type="submit">Envoyer ma demande</button><p className="form-status" aria-live="polite">{status}</p></form></section><MobileActions/></main>;
}
