import {createSign} from "node:crypto";
import type {Appointment} from "./appointment-types";
import {database} from "./db";

const calendarId=process.env.GOOGLE_CALENDAR_ID;const serviceEmail=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;const privateKey=process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,"\n");
const encode=(value:string|Buffer)=>Buffer.from(value).toString("base64url");
async function accessToken(){if(!calendarId||!serviceEmail||!privateKey)return null;const now=Math.floor(Date.now()/1000);const header=encode(JSON.stringify({alg:"RS256",typ:"JWT"}));const payload=encode(JSON.stringify({iss:serviceEmail,scope:"https://www.googleapis.com/auth/calendar",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));const unsigned=`${header}.${payload}`;const signer=createSign("RSA-SHA256");signer.update(unsigned);const assertion=`${unsigned}.${signer.sign(privateKey,"base64url")}`;const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion})});if(!response.ok)throw new Error(`Google token failed (${response.status})`);return String((await response.json()).access_token)}
export async function removeGoogleCalendarEvent(appointment:Appointment){const token=await accessToken();if(!token||!calendarId||!appointment.googleEventId)return {enabled:Boolean(token&&calendarId),synced:false};const base=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`;const response=await fetch(`${base}/${encodeURIComponent(appointment.googleEventId)}`,{method:"DELETE",headers:{authorization:`Bearer ${token}`}});if(!response.ok&&![404,410].includes(response.status))throw new Error(`Google delete failed (${response.status})`);return {enabled:true,synced:true}}
export async function syncGoogleCalendar(appointment:Appointment){const token=await accessToken();if(!token||!calendarId)return {enabled:false,synced:false};const base=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`;if((appointment.status==="cancelled"||appointment.status==="rejected")&&appointment.googleEventId){const response=await fetch(`${base}/${encodeURIComponent(appointment.googleEventId)}`,{method:"DELETE",headers:{authorization:`Bearer ${token}`}});if(!response.ok&&response.status!==410)throw new Error(`Google delete failed (${response.status})`);await saveEventId(appointment.id,null);return {enabled:true,synced:true}}
  if(!appointment.startsAt||!["confirmed","modified"].includes(appointment.status))return {enabled:true,synced:false};const event={summary:`${appointment.requestType} – ${appointment.customerName}`,description:`${appointment.reason}\n\n${appointment.customerPhone}\n${appointment.customerEmail}`,location:appointment.customerAddress,start:{dateTime:appointment.startsAt,timeZone:"Europe/Zurich"},end:{dateTime:appointment.endsAt||new Date(new Date(appointment.startsAt).getTime()+60*60*1000).toISOString(),timeZone:"Europe/Zurich"}};const url=appointment.googleEventId?`${base}/${encodeURIComponent(appointment.googleEventId)}`:base;const response=await fetch(url,{method:appointment.googleEventId?"PATCH":"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(event)});if(!response.ok)throw new Error(`Google event failed (${response.status})`);const result=await response.json();if(!appointment.googleEventId&&result.id)await saveEventId(appointment.id,String(result.id));return {enabled:true,synced:true}}
async function saveEventId(id:string,eventId:string|null){const sql=database();await sql.query("UPDATE appointments SET google_event_id=$2 WHERE id=$1",[id,eventId])}
