"use client";
import {useEffect,useMemo,useState} from "react";
import type {Appointment} from "@/lib/appointment-types";
import {statusLabels} from "@/lib/appointment-types";

type View="day"|"week"|"month"|"list";
const dateKey=(value:string|Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Zurich",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value));
const formatDate=(value:string|null,options:Intl.DateTimeFormatOptions={dateStyle:"medium",timeStyle:"short"})=>value?new Intl.DateTimeFormat("fr-CH",{timeZone:"Europe/Zurich",...options}).format(new Date(value)):"Date à définir";
const localInput=(value:string|null)=>value?new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Zurich",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value)).replace(" ","T"):"";
const phoneHref=(phone:string)=>phone.replace(/[^+\d]/g,"");

export function Dashboard({initialAppointments,initialSelectedId}:{initialAppointments:Appointment[];initialSelectedId?:string}){
  const[appointments,setAppointments]=useState(initialAppointments);const[view,setView]=useState<View>("day");const[query,setQuery]=useState("");const[status,setStatus]=useState("");const[type,setType]=useState("");const[selected,setSelected]=useState<Appointment|null>(()=>initialAppointments.find(item=>item.id===initialSelectedId)||null);const[manual,setManual]=useState(false);const[notice,setNotice]=useState("");
  async function refresh(){const response=await fetch("/api/gestion/rendez-vous",{cache:"no-store"});if(response.ok){const data=await response.json();setAppointments(data.appointments)}}
  useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js");const timer=window.setInterval(refresh,30000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{if(typeof Notification==="undefined"||Notification.permission!=="granted")return;const seen=JSON.parse(sessionStorage.getItem("appointment-notifications")||"[]") as string[];const notify=appointments.filter(item=>!seen.includes(item.id)&&item.status==="new_request");notify.forEach(item=>new Notification("Nouvelle demande Super-Service",{body:`${item.customerName} · ${item.requestType}`}));const now=Date.now();appointments.filter(item=>item.startsAt&&!seen.includes(`soon-${item.id}`)&&new Date(item.startsAt).getTime()>now&&new Date(item.startsAt).getTime()<now+60*60*1000).forEach(item=>{new Notification("Rendez-vous prochain",{body:`${item.customerName} · ${formatDate(item.startsAt)}`});seen.push(`soon-${item.id}`)});sessionStorage.setItem("appointment-notifications",JSON.stringify([...new Set([...seen,...notify.map(item=>item.id)])].slice(-100)))},[appointments]);
  const filtered=useMemo(()=>appointments.filter(item=>{const text=`${item.customerName} ${item.customerEmail} ${item.customerPhone} ${item.reason} ${item.customerAddress}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(!status||item.status===status)&&(!type||item.requestType===type)}),[appointments,query,status,type]);
  const today=dateKey(new Date());const todayItems=filtered.filter(item=>item.startsAt&&dateKey(item.startsAt)===today);const newCount=appointments.filter(item=>item.status==="new_request").length;const types=[...new Set(appointments.map(item=>item.requestType))].sort();
  function open(item:Appointment){setSelected(item);setNotice("")}
  async function move(item:Appointment,day:string){if(!item.startsAt)return;const time=localInput(item.startsAt).slice(11);const start=`${day}T${time}`;let end="";if(item.endsAt){const duration=new Date(item.endsAt).getTime()-new Date(item.startsAt).getTime();const target=new Date(`${start}:00`);end=localInput(new Date(target.getTime()+duration).toISOString())}const response=await fetch(`/api/gestion/rendez-vous/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"propose",startsAt:start,endsAt:end,adminNotes:item.adminNotes||""})});if(response.ok){const data=await response.json();setAppointments(current=>current.map(existing=>existing.id===item.id?data.appointment:existing))}}
  return <div className="admin-app"><header className="admin-top"><div><span className="admin-brand">SUPER-SERVICE</span><p>Gestion des rendez-vous</p></div><div className="top-actions"><button className="notification-button" onClick={()=>Notification.requestPermission()} title="Activer les notifications">🔔</button><form action="/api/gestion/auth/logout" method="post"><button className="admin-ghost">Déconnexion</button></form></div></header><main className="admin-main"><section className="today-hero"><div><p className="admin-kicker">Aujourd’hui</p><h1>{todayItems.length} rendez-vous</h1><p>{newCount?`${newCount} nouvelle${newCount>1?"s":""} demande${newCount>1?"s":""} à traiter`:"Toutes les demandes sont traitées"}</p></div><button className="admin-primary" onClick={()=>setManual(true)}>＋ Ajouter</button></section><section className="admin-tools"><input aria-label="Rechercher" placeholder="Rechercher un client, téléphone, adresse…" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="Filtrer par statut" value={status} onChange={event=>setStatus(event.target.value)}><option value="">Tous les statuts</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select aria-label="Filtrer par type" value={type} onChange={event=>setType(event.target.value)}><option value="">Tous les types</option>{types.map(value=><option value={value} key={value}>{value}</option>)}</select></section><nav className="view-tabs" aria-label="Vue calendrier">{(["day","week","month","list"] as View[]).map(value=><button key={value} className={view===value?"active":""} onClick={()=>setView(value)}>{{day:"Jour",week:"Semaine",month:"Mois",list:"Liste"}[value]}</button>)}</nav><CalendarContent view={view} appointments={filtered} onOpen={open} onMove={move}/></main><footer className="admin-bottom"><button className={view==="day"?"active":""} onClick={()=>setView("day")}><span>⌂</span>Accueil</button><button className={view!=="day"?"active":""} onClick={()=>setView("month")}><span>▦</span>Calendrier</button><button onClick={()=>{setStatus("new_request");setView("list")}}><span className="counter-icon">◎{newCount>0&&<b>{newCount}</b>}</span>Demandes</button><button onClick={()=>setManual(true)}><span>＋</span>Ajouter</button></footer>{selected&&<AppointmentPanel appointment={selected} onClose={()=>setSelected(null)} onSaved={item=>{setAppointments(current=>current.map(existing=>existing.id===item.id?item:existing));setSelected(item)}} notice={notice} setNotice={setNotice}/>} {manual&&<ManualForm onClose={()=>setManual(false)} onCreated={item=>{setAppointments(current=>[item,...current]);setManual(false)}}/>}</div>
}

function CalendarContent({view,appointments,onOpen,onMove}:{view:View;appointments:Appointment[];onOpen:(item:Appointment)=>void;onMove:(item:Appointment,day:string)=>void}){const today=new Date();if(view==="day")return <AppointmentList title="Rendez-vous du jour" items={appointments.filter(item=>item.startsAt&&dateKey(item.startsAt)===dateKey(today))} onOpen={onOpen}/>;if(view==="list")return <AppointmentList title="Prochains rendez-vous et demandes" items={appointments} onOpen={onOpen}/>;if(view==="week"){const monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7));const days=Array.from({length:7},(_,index)=>{const day=new Date(monday);day.setDate(monday.getDate()+index);return day});return <section className="week-grid">{days.map(day=><div className={dateKey(day)===dateKey(today)?"week-day current":"week-day"} key={dateKey(day)} onDragOver={event=>event.preventDefault()} onDrop={event=>{const item=appointments.find(value=>value.id===event.dataTransfer.getData("text/appointment"));if(item)onMove(item,dateKey(day))}}><h3>{formatDate(day.toISOString(),{weekday:"short",day:"numeric"})}</h3>{appointments.filter(item=>item.startsAt&&dateKey(item.startsAt)===dateKey(day)).map(item=><button draggable onDragStart={event=>event.dataTransfer.setData("text/appointment",item.id)} className={`mini-event status-${item.status}`} key={item.id} onClick={()=>onOpen(item)}><strong>{formatDate(item.startsAt,{hour:"2-digit",minute:"2-digit"})}</strong>{item.customerName}</button>)}</div>)}</section>}
  const first=new Date(today.getFullYear(),today.getMonth(),1);const offset=(first.getDay()+6)%7;const start=new Date(first);start.setDate(1-offset);const days=Array.from({length:42},(_,index)=>{const day=new Date(start);day.setDate(start.getDate()+index);return day});return <section className="month-calendar"><div className="month-title">{formatDate(today.toISOString(),{month:"long",year:"numeric"})}</div><div className="month-grid">{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map(label=><b className="weekday" key={label}>{label}</b>)}{days.map(day=>{const events=appointments.filter(item=>item.startsAt&&dateKey(item.startsAt)===dateKey(day));return <div className={`month-day ${day.getMonth()!==today.getMonth()?"muted":""} ${dateKey(day)===dateKey(today)?"current":""}`} key={dateKey(day)} onDragOver={event=>event.preventDefault()} onDrop={event=>{const item=appointments.find(value=>value.id===event.dataTransfer.getData("text/appointment"));if(item)onMove(item,dateKey(day))}}><span>{day.getDate()}</span>{events.slice(0,3).map(item=><button draggable onDragStart={event=>event.dataTransfer.setData("text/appointment",item.id)} key={item.id} onClick={()=>onOpen(item)} title={item.customerName}>{item.customerName}</button>)}{events.length>3&&<small>+{events.length-3}</small>}</div>})}</div></section>}

function AppointmentList({title,items,onOpen}:{title:string;items:Appointment[];onOpen:(item:Appointment)=>void}){return <section><div className="section-heading"><h2>{title}</h2><span>{items.length}</span></div><div className="appointment-list">{items.length===0?<div className="empty-state">Aucun rendez-vous dans cette vue.</div>:items.map(item=><article className="appointment-card" key={item.id}><button className="card-main" onClick={()=>onOpen(item)}><span className={`status-dot status-${item.status}`}/><span><strong>{item.customerName}</strong><small>{item.requestType} · {item.reason}</small><small>{item.startsAt?formatDate(item.startsAt):`Souhaité le ${item.preferredDate}${item.preferredTimeStart?` à ${item.preferredTimeStart}`:""}`}</small></span><em>{statusLabels[item.status]}</em></button><div className="quick-actions"><a href={`tel:${phoneHref(item.customerPhone)}`}>Appeler</a><a href={`https://wa.me/${phoneHref(item.customerPhone).replace("+","")}`} target="_blank">WhatsApp</a>{item.status==="new_request"&&<button onClick={()=>onOpen(item)}>Traiter</button>}</div></article>)}</div></section>}

function AppointmentPanel({appointment,onClose,onSaved,notice,setNotice}:{appointment:Appointment;onClose:()=>void;onSaved:(item:Appointment)=>void;notice:string;setNotice:(value:string)=>void}){const[start,setStart]=useState(localInput(appointment.startsAt)||`${appointment.preferredDate}T${appointment.preferredTimeStart||"09:00"}`);const[end,setEnd]=useState(localInput(appointment.endsAt));const[notes,setNotes]=useState(appointment.adminNotes||"");const[saving,setSaving]=useState(false);async function act(action:string){setSaving(true);setNotice("");const response=await fetch(`/api/gestion/rendez-vous/${appointment.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,startsAt:start,endsAt:end,adminNotes:notes})});const data=await response.json();setSaving(false);if(response.ok){onSaved(data.appointment);setNotice(data.emailSent===false?"Enregistré, mais l’e-mail au client n’a pas pu être envoyé.":"Modification enregistrée et client informé.")}else setNotice(data.error||"Impossible d’enregistrer")}
  return <div className="panel-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><aside className="detail-panel"><button className="panel-close" onClick={onClose}>×</button><span className={`status-pill status-${appointment.status}`}>{statusLabels[appointment.status]}</span><h2>{appointment.customerName}</h2><p className="detail-reason">{appointment.requestType} — {appointment.reason}</p><div className="contact-buttons"><a href={`tel:${phoneHref(appointment.customerPhone)}`}>☎ Appeler</a><a href={`https://wa.me/${phoneHref(appointment.customerPhone).replace("+","")}`} target="_blank">WhatsApp</a><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(appointment.customerAddress)}`} target="_blank">Itinéraire</a></div><dl><dt>E-mail</dt><dd><a href={`mailto:${appointment.customerEmail}`}>{appointment.customerEmail}</a></dd><dt>Téléphone</dt><dd>{appointment.customerPhone}</dd><dt>Adresse</dt><dd>{appointment.customerAddress}</dd><dt>Date demandée</dt><dd>{appointment.preferredDate} {appointment.preferredTimeStart||""}</dd>{appointment.alternateDate&&<><dt>Deuxième choix</dt><dd>{appointment.alternateDate} {appointment.alternateTimeStart||""}</dd></>}<dt>Origine</dt><dd>{appointment.source==="client"?"Demande client":"Ajout manuel"}</dd></dl><label>Date et heure de début<input type="datetime-local" value={start} onChange={event=>setStart(event.target.value)}/></label><label>Fin ou durée estimée<input type="datetime-local" value={end} onChange={event=>setEnd(event.target.value)}/></label><label>Notes internes<textarea rows={4} value={notes} onChange={event=>setNotes(event.target.value)}/></label>{notice&&<p className="panel-notice">{notice}</p>}<div className="decision-buttons"><button className="accept" disabled={saving} onClick={()=>act("accept")}>Accepter</button><button className="modify" disabled={saving} onClick={()=>act("propose")}>Proposer cette date</button><button disabled={saving} onClick={()=>act("notes")}>Enregistrer les notes</button><button className="danger" disabled={saving} onClick={()=>act("reject")}>Refuser</button><button className="danger ghost" disabled={saving} onClick={()=>act("cancel")}>Annuler le rendez-vous</button></div></aside></div>}

function ManualForm({onClose,onCreated}:{onClose:()=>void;onCreated:(item:Appointment)=>void}){const[saving,setSaving]=useState(false);const[error,setError]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const body=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/gestion/rendez-vous",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setSaving(false);if(response.ok)onCreated(data.appointment);else setError(data.error||"Création impossible")};return <div className="panel-backdrop"><aside className="detail-panel"><button className="panel-close" onClick={onClose}>×</button><h2>Nouveau rendez-vous</h2><form className="manual-form" onSubmit={submit}><label>Nom et prénom<input name="name" required/></label><label>E-mail<input type="email" name="email" required/></label><label>Téléphone<input name="phone" required/></label><label>Adresse<input name="address" required/></label><label>Type<select name="requestType" required><option>visite</option><option>demenagement</option><option>nettoyage</option><option>travaux</option><option>livraison</option><option>debarras</option><option>autre</option></select></label><label>Motif<textarea name="reason" required/></label><label>Début<input type="datetime-local" name="startsAt" required/></label><label>Fin<input type="datetime-local" name="endsAt"/></label><label>Notes internes<textarea name="adminNotes"/></label>{error&&<p className="admin-error">{error}</p>}<button className="admin-primary" disabled={saving}>{saving?"Création…":"Créer le rendez-vous"}</button></form></aside></div>}
